import { Product, SupplyItem, SupplyRequest, Expense, PricingRecipe, CashShift } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Latte Ammm Lavanda & Vainilla',
    description: 'Espresso de especialidad, leche vaporizada, notas florales de lavanda y extracto natural de vainilla.',
    category: 'cafe',
    price: 68,
    cost: 16.5,
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: false,
    modifierGroups: [
      {
        id: 'mod-size',
        name: 'Tamaño',
        required: true,
        multiSelect: false,
        options: [
          { id: 'size-12', name: 'Mediano (12 oz)', priceDelta: 0 },
          { id: 'size-16', name: 'Grande (16 oz)', priceDelta: 12 },
        ],
      },
      {
        id: 'mod-milk',
        name: 'Tipo de Leche',
        required: true,
        multiSelect: false,
        options: [
          { id: 'milk-entera', name: 'Entera', priceDelta: 0 },
          { id: 'milk-deslac', name: 'Deslactosada Light', priceDelta: 0 },
          { id: 'milk-avena', name: 'Avena Barista', priceDelta: 14 },
          { id: 'milk-almendra', name: 'Almendra sin azúcar', priceDelta: 14 },
        ],
      },
      {
        id: 'mod-temp',
        name: 'Temperatura',
        required: true,
        multiSelect: false,
        options: [
          { id: 'temp-hot', name: 'Caliente', priceDelta: 0 },
          { id: 'temp-ice', name: 'Con Hielo (Iced)', priceDelta: 5 },
        ],
      },
      {
        id: 'mod-extra',
        name: 'Extras',
        required: false,
        multiSelect: true,
        options: [
          { id: 'ext-shot', name: 'Extra Shot Espresso', priceDelta: 15 },
          { id: 'ext-jarabe', name: 'Jarabe Extra', priceDelta: 10 },
        ],
      },
    ],
  },
  {
    id: 'prod-2',
    name: 'Flat White Sedoso',
    description: 'Doble ristretto con microespuma de leche aterciopelada en taza de cerámica de 6 oz.',
    category: 'cafe',
    price: 55,
    cost: 12.0,
    imageUrl: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: false,
    modifierGroups: [
      {
        id: 'mod-milk-fw',
        name: 'Tipo de Leche',
        required: true,
        multiSelect: false,
        options: [
          { id: 'milk-entera', name: 'Entera', priceDelta: 0 },
          { id: 'milk-deslac', name: 'Deslactosada', priceDelta: 0 },
          { id: 'milk-avena', name: 'Avena Barista', priceDelta: 14 },
        ],
      },
    ],
  },
  {
    id: 'prod-3',
    name: 'Espresso Doble Origen',
    description: 'Extracción 1:2 con granos de Chiapas / Oaxaca con notas a chocolate amargo y cítricos dulces.',
    category: 'cafe',
    price: 42,
    cost: 7.5,
    imageUrl: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: false,
  },
  {
    id: 'prod-4',
    name: 'Matcha Latte Ceremonial',
    description: 'Matcha grado ceremonial de Uji con leche vaporizada y un toque sutil de miel de agave.',
    category: 'cafe',
    price: 72,
    cost: 19.0,
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: false,
    modifierGroups: [
      {
        id: 'mod-temp-m',
        name: 'Temperatura',
        required: true,
        multiSelect: false,
        options: [
          { id: 'temp-hot', name: 'Caliente', priceDelta: 0 },
          { id: 'temp-ice', name: 'Iced con Hielo', priceDelta: 5 },
          { id: 'temp-frappe', name: 'Frappé Matcha', priceDelta: 15 },
        ],
      },
      {
        id: 'mod-milk-m',
        name: 'Leche',
        required: true,
        multiSelect: false,
        options: [
          { id: 'milk-entera', name: 'Entera', priceDelta: 0 },
          { id: 'milk-avena', name: 'Avena', priceDelta: 14 },
          { id: 'milk-almendra', name: 'Almendra', priceDelta: 14 },
        ],
      },
    ],
  },
  {
    id: 'prod-5',
    name: 'Cold Brew Tonic & Cítricos',
    description: 'Maceración en frío por 18 hrs, servido sobre hielo con agua tónica premium y rodaja de naranja deshidratada.',
    category: 'bebidas_frias',
    price: 65,
    cost: 14.2,
    imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: false,
  },
  {
    id: 'prod-6',
    name: 'Croissant Mantequilla Almendrado',
    description: 'Hojaldre artesanal con mantequilla francesa, relleno de crema frangipane y cubierto de almendras tostadas.',
    category: 'panaderia',
    price: 52,
    cost: 18.0,
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: true,
    stockQuantity: 12,
  },
  {
    id: 'prod-7',
    name: 'Rol de Canela & Cardamomo Glaseado',
    description: 'Masa brioche suave horneada con infusión de cardamomo fresco, canela de Ceilán y glaseado de queso crema.',
    category: 'panaderia',
    price: 48,
    cost: 14.5,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: true,
    stockQuantity: 4, // Alerta stock bajo!
  },
  {
    id: 'prod-8',
    name: 'Pain au Chocolat Belga',
    description: 'Dos barras de chocolate amargo 60% cacao envueltas en capas crujientes y doradas de masa hojaldrada.',
    category: 'panaderia',
    price: 49,
    cost: 15.0,
    imageUrl: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: true,
    stockQuantity: 8,
  },
  {
    id: 'prod-9',
    name: 'Focaccia Serrano, Pesto & Burrata',
    description: 'Focaccia de romero y aceite de oliva virgen extra, rellena de jamón serrano, pesto genovés de albahaca y burrata fresca.',
    category: 'bocados',
    price: 110,
    cost: 42.0,
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: true,
    stockQuantity: 6,
  },
  {
    id: 'prod-10',
    name: 'Avocado Toast & Huevo Poché',
    description: 'Rebanada de masa madre rústica, puré cremoso de aguacate hass, huevo pochado, hojuelas de chile y brotes orgánicos.',
    category: 'bocados',
    price: 95,
    cost: 31.0,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: true,
    stockQuantity: 10,
  },
  {
    id: 'prod-11',
    name: 'Tarta Tartín de Manzana Caramelizada',
    description: 'Manzanas horneadas al caramelo con fondo hojaldrado crocante y toque de sal marina.',
    category: 'postres',
    price: 65,
    cost: 21.0,
    imageUrl: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: true,
    stockQuantity: 2, // Crítico
  },
  {
    id: 'prod-12',
    name: 'Combo Ammm Mañanero',
    description: 'Café Latte o Americano Mediano + Croissant de Mantequilla o Rol de Canela.',
    category: 'paquetes',
    price: 98,
    cost: 28.0,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isDirectStock: false,
  },
];

export const INITIAL_SUPPLIES: SupplyItem[] = [
  {
    id: 'sup-1',
    name: 'Café en Grano Especialidad (Mezcla Ammm Chiapas/Oaxaca)',
    unit: 'kg',
    currentStock: 3.2,
    minStock: 5.0, // Alerta
    unitCost: 320,
    category: 'cafe_grano',
    lastRestocked: '2026-09-24',
  },
  {
    id: 'sup-2',
    name: 'Leche Entera de Origen Local',
    unit: 'L',
    currentStock: 14,
    minStock: 12,
    unitCost: 26,
    category: 'lacteos',
    lastRestocked: '2026-09-28',
  },
  {
    id: 'sup-3',
    name: 'Leche de Avena Edición Barista',
    unit: 'L',
    currentStock: 3,
    minStock: 6, // Alerta
    unitCost: 58,
    category: 'lacteos',
    lastRestocked: '2026-09-26',
  },
  {
    id: 'sup-4',
    name: 'Leche de Almendra sin Azúcar',
    unit: 'L',
    currentStock: 5,
    minStock: 4,
    unitCost: 52,
    category: 'lacteos',
    lastRestocked: '2026-09-27',
  },
  {
    id: 'sup-5',
    name: 'Jarabe Artesanal de Lavanda & Vainilla',
    unit: 'L',
    currentStock: 1.8,
    minStock: 1.0,
    unitCost: 180,
    category: 'jarabes',
    lastRestocked: '2026-09-20',
  },
  {
    id: 'sup-6',
    name: 'Matcha Uji Ceremonial (Bote 500g)',
    unit: 'kg',
    currentStock: 0.45,
    minStock: 0.3,
    unitCost: 1250,
    category: 'jarabes',
    lastRestocked: '2026-09-15',
  },
  {
    id: 'sup-7',
    name: 'Vasos Compostables 12 oz + Tapa blanca',
    unit: 'piezas',
    currentStock: 80,
    minStock: 150, // Alerta
    unitCost: 3.2,
    category: 'desechables',
    lastRestocked: '2026-09-22',
  },
  {
    id: 'sup-8',
    name: 'Vasos Compostables 16 oz + Tapa',
    unit: 'piezas',
    currentStock: 190,
    minStock: 100,
    unitCost: 3.8,
    category: 'desechables',
    lastRestocked: '2026-09-25',
  },
  {
    id: 'sup-9',
    name: 'Servilletas de papel kraft reciclado',
    unit: 'paquetes',
    currentStock: 6,
    minStock: 4,
    unitCost: 45,
    category: 'desechables',
    lastRestocked: '2026-09-28',
  },
];

export const INITIAL_SUPPLY_REQUESTS: SupplyRequest[] = [
  {
    id: 'req-1',
    supplyName: 'Leche de Avena Barista',
    quantityNeeded: '1 caja (12 L)',
    notes: 'Nos quedan solo 3 botes en refrigerador y es la que más piden en el turno de la mañana.',
    urgency: 'alta',
    requestedBy: 'Sofía M. (Barista)',
    requestedAt: '2026-09-30 09:15',
    status: 'pendiente',
  },
  {
    id: 'req-2',
    supplyName: 'Vasos 12 oz para llevar',
    quantityNeeded: '2 mangas (100 pzas)',
    notes: 'Quedan menos de 80 vasos en barra.',
    urgency: 'alta',
    requestedBy: 'Carlos R. (Cajero)',
    requestedAt: '2026-09-30 10:30',
    status: 'pendiente',
  },
  {
    id: 'req-3',
    supplyName: 'Café en Grano Chiapas Especialidad',
    quantityNeeded: '5 kg',
    notes: 'Quedan 3.2 kg, estimado para 2 días.',
    urgency: 'media',
    requestedBy: 'Sofía M. (Barista)',
    requestedAt: '2026-09-29 18:20',
    status: 'comprado',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    description: 'Compra semanal de insumos panadería y lácteos',
    category: 'insumos',
    amount: 1450,
    type: 'variable',
    date: '2026-09-29',
    paidVia: 'transferencia',
    notes: 'Proveedor Santa Clara y harinas artesanales',
  },
  {
    id: 'exp-2',
    description: 'Luz y electricidad local (CFE)',
    category: 'servicios',
    amount: 2850,
    type: 'fijo',
    date: '2026-09-25',
    paidVia: 'transferencia',
  },
  {
    id: 'exp-3',
    description: 'Internet de fibra óptica simétrica',
    category: 'servicios',
    amount: 699,
    type: 'fijo',
    date: '2026-09-20',
    paidVia: 'tarjeta',
  },
  {
    id: 'exp-4',
    description: 'Mantenimiento preventivo máquina espresso La Marzocco',
    category: 'mantenimiento',
    amount: 1200,
    type: 'variable',
    date: '2026-09-18',
    paidVia: 'transferencia',
  },
  {
    id: 'exp-5',
    description: 'Compra de bolsas kraft y stickers de logo Ammm',
    category: 'insumos',
    amount: 850,
    type: 'variable',
    date: '2026-09-27',
    paidVia: 'efectivo',
  },
];

export const INITIAL_RECIPES: PricingRecipe[] = [
  {
    id: 'rec-1',
    productName: 'Latte Ammm Lavanda (12 oz)',
    category: 'cafe',
    ingredients: [
      { id: 'ing-1', name: 'Café en grano (18g)', quantity: '18g', cost: 5.76 },
      { id: 'ing-2', name: 'Leche entera fresca (220ml)', quantity: '220ml', cost: 5.72 },
      { id: 'ing-3', name: 'Jarabe Lavanda-Vainilla (25ml)', quantity: '25ml', cost: 4.50 },
    ],
    packagingCost: 3.50, // Vaso compostable + tapa + fajilla
    wastePercentage: 5, // 5% de merma en purga de molino y leche
    currentSellingPrice: 68,
    targetMarginPercentage: 70, // 70% de margen bruto deseado
  },
  {
    id: 'rec-2',
    productName: 'Focaccia Serrano & Burrata',
    category: 'bocados',
    ingredients: [
      { id: 'ing-21', name: 'Focaccia artesanal masa madre', quantity: '1 pieza', cost: 12.00 },
      { id: 'ing-22', name: 'Jamón serrano reserva (60g)', quantity: '60g', cost: 18.00 },
      { id: 'ing-23', name: 'Burrata fresca (80g)', quantity: '80g', cost: 16.00 },
      { id: 'ing-24', name: 'Pesto casero de albahaca (20g)', quantity: '20g', cost: 5.50 },
    ],
    packagingCost: 4.00,
    wastePercentage: 4,
    currentSellingPrice: 110,
    targetMarginPercentage: 65,
  },
  {
    id: 'rec-3',
    productName: 'Croissant Frangipane Almendrado',
    category: 'panaderia',
    ingredients: [
      { id: 'ing-31', name: 'Croissant base mantequilla francesa', quantity: '1 pza', cost: 9.50 },
      { id: 'ing-32', name: 'Crema frangipane almendra (45g)', quantity: '45g', cost: 6.80 },
      { id: 'ing-33', name: 'Almendras fileteadas tostadas', quantity: '15g', cost: 3.20 },
    ],
    packagingCost: 2.20,
    wastePercentage: 3,
    currentSellingPrice: 52,
    targetMarginPercentage: 68,
  },
];

export const INITIAL_ACTIVE_SHIFT: CashShift = {
  id: 'shift-today',
  openedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  initialCash: 1000, // Fondo de caja con el que abrió
  cashSales: 1840,
  cardSales: 2150,
  transferSales: 430,
  cashIn: 200, // Cambio traído del banco
  cashOut: 150, // Compra de hielo de emergencia en Oxxo
  movements: [
    {
      id: 'mov-1',
      type: 'entrada',
      amount: 200,
      reason: 'Monedas de $5 y $10 para cambio',
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'mov-2',
      type: 'salida',
      amount: 150,
      reason: 'Bolsa de hielo extra por alta afluencia',
      timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
  ],
  expectedCash: 1000 + 1840 + 200 - 150, // 2890
  collaborator: 'Sofía Méndez',
  status: 'abierta',
};
